# Builder stage
FROM maven:3.9.6-openjdk-17 AS Builder
WORKDIR /app
COPY ./pom.xml .
COPY ./src ./src
RUN mvn clean package

# Final image stage
FROM openjdk:17-jdk-alpine
WORKDIR /app
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY --from=Builder /app/${JAR_FILE} RegistrationService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "RegistrationService-0.0.1-SNAPSHOT.jar"]
